# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/gui/main_ocr.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1229, 652)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.brows_btn = QtWidgets.QPushButton(self.centralwidget)
        self.brows_btn.setGeometry(QtCore.QRect(1080, 570, 87, 27))
        self.brows_btn.setObjectName("brows_btn")
        self.display_selected_file = QtWidgets.QTextBrowser(self.centralwidget)
        self.display_selected_file.setGeometry(QtCore.QRect(400, 570, 661, 31))
        self.display_selected_file.setObjectName("display_selected_file")
        self.img_display = QtWidgets.QLabel(self.centralwidget)
        self.img_display.setGeometry(QtCore.QRect(380, 50, 811, 471))
        self.img_display.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.img_display.setFrameShadow(QtWidgets.QFrame.Plain)
        self.img_display.setMidLineWidth(1)
        self.img_display.setText("")
        self.img_display.setObjectName("img_display")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 50, 327, 429))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 325, 427))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.laplacian_cbx = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.laplacian_cbx.setObjectName("laplacian_cbx")
        self.gridLayout.addWidget(self.laplacian_cbx, 0, 0, 1, 1)
        self.laplacian_8_cbx = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.laplacian_8_cbx.setObjectName("laplacian_8_cbx")
        self.gridLayout.addWidget(self.laplacian_8_cbx, 1, 0, 1, 1)
        self.laplacian_rob_cbx = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.laplacian_rob_cbx.setObjectName("laplacian_rob_cbx")
        self.gridLayout.addWidget(self.laplacian_rob_cbx, 2, 0, 1, 1)
        self.gauss_cbx = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.gauss_cbx.setObjectName("gauss_cbx")
        self.gridLayout.addWidget(self.gauss_cbx, 3, 0, 1, 1)
        self.mean_cbx = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.mean_cbx.setObjectName("mean_cbx")
        self.gridLayout.addWidget(self.mean_cbx, 4, 0, 1, 1)
        self.mean_voisinage = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.mean_voisinage.setObjectName("mean_voisinage")
        self.gridLayout.addWidget(self.mean_voisinage, 4, 2, 1, 1)
        self.median_cbx = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.median_cbx.setObjectName("median_cbx")
        self.gridLayout.addWidget(self.median_cbx, 5, 0, 1, 1)
        self.median_value = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.median_value.setObjectName("median_value")
        self.gridLayout.addWidget(self.median_value, 5, 2, 1, 1)
        self.delate_cbx = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.delate_cbx.setObjectName("delate_cbx")
        self.gridLayout.addWidget(self.delate_cbx, 6, 0, 1, 1)
        self.delate_value = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.delate_value.setObjectName("delate_value")
        self.gridLayout.addWidget(self.delate_value, 6, 2, 1, 1)
        self.erode_cbx = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.erode_cbx.setObjectName("erode_cbx")
        self.gridLayout.addWidget(self.erode_cbx, 7, 0, 1, 1)
        self.erode_value = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.erode_value.setObjectName("erode_value")
        self.gridLayout.addWidget(self.erode_value, 7, 2, 1, 1)
        self.ouverture_cbx = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.ouverture_cbx.setObjectName("ouverture_cbx")
        self.gridLayout.addWidget(self.ouverture_cbx, 8, 0, 1, 1)
        self.ouverture_value = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.ouverture_value.setObjectName("ouverture_value")
        self.gridLayout.addWidget(self.ouverture_value, 8, 2, 1, 1)
        self.fermeture_cbx = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.fermeture_cbx.setObjectName("fermeture_cbx")
        self.gridLayout.addWidget(self.fermeture_cbx, 9, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 10, 0, 1, 1)
        self.adapt_th_int_img_cbx = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.adapt_th_int_img_cbx.setObjectName("adapt_th_int_img_cbx")
        self.gridLayout.addWidget(self.adapt_th_int_img_cbx, 11, 0, 1, 2)
        self.otsu_cbx = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.otsu_cbx.setObjectName("otsu_cbx")
        self.gridLayout.addWidget(self.otsu_cbx, 12, 0, 1, 1)
        self.fermeture_value = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.fermeture_value.setObjectName("fermeture_value")
        self.gridLayout.addWidget(self.fermeture_value, 9, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 6, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 7, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 8, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 9, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.apply_btn = QtWidgets.QPushButton(self.centralwidget)
        self.apply_btn.setGeometry(QtCore.QRect(90, 530, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.apply_btn.setFont(font)
        self.apply_btn.setObjectName("apply_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1229, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.brows_btn.setText(_translate("MainWindow", "Browse"))
        self.laplacian_cbx.setText(_translate("MainWindow", "Laplacian filter"))
        self.laplacian_8_cbx.setText(_translate("MainWindow", "laplacien 8 connec"))
        self.laplacian_rob_cbx.setText(_translate("MainWindow", "Laplacin robinson"))
        self.gauss_cbx.setText(_translate("MainWindow", "Gaussian filter"))
        self.mean_cbx.setText(_translate("MainWindow", "Mean filter"))
        self.median_cbx.setText(_translate("MainWindow", "Median filter"))
        self.delate_cbx.setText(_translate("MainWindow", "delate function"))
        self.erode_cbx.setText(_translate("MainWindow", "Erode function"))
        self.ouverture_cbx.setText(_translate("MainWindow", "Ouvertuer function"))
        self.fermeture_cbx.setText(_translate("MainWindow", "fermeture function"))
        self.label.setText(_translate("MainWindow", "Binarisation"))
        self.adapt_th_int_img_cbx.setText(_translate("MainWindow", "Adaptative threashold integral img"))
        self.otsu_cbx.setText(_translate("MainWindow", "otsu binarisation"))
        self.label_2.setText(_translate("MainWindow", "voisinage"))
        self.label_3.setText(_translate("MainWindow", "voisinage"))
        self.label_4.setText(_translate("MainWindow", "taille"))
        self.label_5.setText(_translate("MainWindow", "taille"))
        self.label_6.setText(_translate("MainWindow", "taille"))
        self.label_7.setText(_translate("MainWindow", "taille"))
        self.apply_btn.setText(_translate("MainWindow", "Apply "))

